# Generated by Django 6.0 on 2025-12-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("task", models.CharField(max_length=20)),
                ("n_samples", models.IntegerField()),
                ("n_features", models.IntegerField()),
                ("n_classes", models.IntegerField(blank=True, null=True)),
                ("class_labels", models.JSONField(blank=True, null=True)),
                ("feature_names", models.JSONField(blank=True, null=True)),
                (
                    "target_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
