# Generated by Django 6.0 on 2025-12-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Algorithm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("classical", "Classical (sklearn/xgboost)"),
                            ("deep", "Deep (PyTorch)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("hyperparameter_specs", models.JSONField(default=list)),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
