# Generated by Django 6.0 on 2026-02-14 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml_api", "0003_experiment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="algorithm",
            name="hyperparameter_specs",
        ),
        migrations.RemoveField(
            model_name="experiment",
            name="algorithm",
        ),
        migrations.CreateModel(
            name="AlgorithmVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("supported_tasks", models.JSONField(default=list)),
                ("hyperparameter_specs", models.JSONField(default=list)),
                (
                    "algorithm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="ml_api.algorithm",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="experiment",
            name="algorithm_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="experiments",
                to="ml_api.algorithmvariant",
            ),
        ),
    ]
